---
version: 2

project_name: rcon

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: SRS-Hosting
    name: rcon

dockers_v2:
  - images:
      - "ghcr.io/srs-hosting/rcon"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.licenses": MIT
      "org.opencontainers.image.url": "https://github.com/SRS-Hosting/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/SRS-Hosting/{{ .ProjectName }}"
    flags:
      - "--pull"

builds:
  - main: ./cmd/rcon
    binary: rcon
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
      - mips
    goarm:
      - "6"
      - "7"
    gomips:
      - "softfloat"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: riscv64
      - goos: windows
        goarch: mips
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}

milestones:
  - close: true
