// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type configShadow struct {
	Address        *string `json:"address" toml:"address" yaml:"address"`
	Host           *string `json:"host" toml:"host" yaml:"host"`
	Port           *int    `json:"port" toml:"port" yaml:"port"`
	Password       *string `json:"password" toml:"password" yaml:"password"`
	TimeoutSeconds *int    `json:"timeoutSeconds" toml:"timeoutSeconds" yaml:"timeoutSeconds"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.Host = "127.0.0.1"
	set("host", configulator.LayerDefault, "default tag")
	cfg.Port = 27015
	set("port", configulator.LayerDefault, "default tag")
	cfg.TimeoutSeconds = 10
	set("timeoutSeconds", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.Address != nil {
		cfg.Address = *s.Address
		set("address", configulator.LayerFile, file)
	}
	if s.Host != nil {
		cfg.Host = *s.Host
		set("host", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.Password != nil {
		cfg.Password = *s.Password
		set("password", configulator.LayerFile, file)
	}
	if s.TimeoutSeconds != nil {
		cfg.TimeoutSeconds = *s.TimeoutSeconds
		set("timeoutSeconds", configulator.LayerFile, file)
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Address = v
			set("address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "host"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Host = v
			set("host", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Port = int(p)
			set("port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "password"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Password = v
			set("password", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "timeoutSeconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "timeoutSeconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.TimeoutSeconds = int(p)
			set("timeoutSeconds", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"address"}, o.Separator), strings.Join([]string{"host"}, o.Separator), strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"password"}, o.Separator), strings.Join([]string{"timeoutSeconds"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"address"}, o.Separator), "", "address of the RCON server as host:port; overrides host and port")
	fs.String(strings.Join([]string{"host"}, o.Separator), "127.0.0.1", "hostname or IP of the RCON server")
	fs.Int(strings.Join([]string{"port"}, o.Separator), 27015, "TCP port of the RCON server")
	fs.String(strings.Join([]string{"password"}, o.Separator), "", "RCON password; prefer the environment variable over an argument")
	fs.Int(strings.Join([]string{"timeoutSeconds"}, o.Separator), 10, "deadline in seconds covering a whole RCON exchange: connect, authenticate, command, response")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "address",
				Source: "--" + n,
			}
		}
		cfg.Address = v
		set("address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"host"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "host",
				Source: "--" + n,
			}
		}
		cfg.Host = v
		set("host", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"password"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "password",
				Source: "--" + n,
			}
		}
		cfg.Password = v
		set("password", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"timeoutSeconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeoutSeconds",
				Source: "--" + n,
			}
		}
		cfg.TimeoutSeconds = v
		set("timeoutSeconds", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Address = &str
			default:
				return fmt.Errorf("address: expected a string, got %v", v.Kind())
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Host = &str
			default:
				return fmt.Errorf("host: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Password = &str
			default:
				return fmt.Errorf("password: expected a string, got %v", v.Kind())
			}
		case "timeoutSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.TimeoutSeconds = &val
			default:
				return fmt.Errorf("timeoutSeconds: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("address = %v\n", c.Address))
	b.WriteString(fmt.Sprintf("host = %v\n", c.Host))
	b.WriteString(fmt.Sprintf("port = %v\n", c.Port))
	b.WriteString("password = (redacted)\n")
	b.WriteString(fmt.Sprintf("timeoutSeconds = %v\n", c.TimeoutSeconds))
	return b.String()
}
