// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type configShadow struct {
	Address        *string `json:"address"        toml:"address"        yaml:"address"`
	Host           *string `json:"host"           toml:"host"           yaml:"host"`
	Port           *int    `json:"port"           toml:"port"           yaml:"port"`
	Password       *string `json:"password"       toml:"password"       yaml:"password"`
	TimeoutSeconds *int    `json:"timeoutSeconds" toml:"timeoutSeconds" yaml:"timeoutSeconds"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.Host = "127.0.0.1"
	set("host", configulator.LayerDefault, "default tag")
	cfg.Port = 27015
	set("port", configulator.LayerDefault, "default tag")
	cfg.TimeoutSeconds = 10
	set("timeoutSeconds", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.Address != nil {
		cfg.Address = *s.Address
		set("address", configulator.LayerFile, file)
	}
	if s.Host != nil {
		cfg.Host = *s.Host
		set("host", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.Password != nil {
		cfg.Password = *s.Password
		set("password", configulator.LayerFile, file)
	}
	if s.TimeoutSeconds != nil {
		cfg.TimeoutSeconds = *s.TimeoutSeconds
		set("timeoutSeconds", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "address"); ok {
		cfg.Address = v
		set("address", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "host"); ok {
		cfg.Host = v
		set("host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = int(p)
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "password"); ok {
		cfg.Password = v
		set("password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "timeoutSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeoutSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.TimeoutSeconds = int(p)
		set("timeoutSeconds", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, _ *cpflag.Options) error {
	names := []string{
		"address",
		"host",
		"port",
		"password",
		"timeoutSeconds",
	}
	shorts := []string{"a", "H", "P", "p", ""}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
		if s := shorts[i]; s != "" {
			if f := fs.ShorthandLookup(s); f != nil {
				return &configulator.FlagConflictError{
					Existing:  f.Name,
					Flag:      name,
					Shorthand: s,
				}
			}
		}
	}
	fs.StringP(names[0], "a", "", "address of the RCON server as host:port; overrides host and port")
	fs.StringP(names[1], "H", "127.0.0.1", "hostname or IP of the RCON server")
	fs.VarP(impl.NewInt(27015), names[2], "P", "TCP port of the RCON server")
	fs.StringP(names[3], "p", "", "RCON password; prefer the environment variable over an argument")
	fs.Var(impl.NewInt(10), names[4], "deadline in seconds covering a whole RCON exchange: connect, authenticate, command, response")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, _ *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "address"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "address",
				Source: "--" + n,
			}
		}
		cfg.Address = v
		set("address", configulator.LayerCLI, "--"+n)
	}
	if n := "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "host",
				Source: "--" + n,
			}
		}
		cfg.Host = v
		set("host", configulator.LayerCLI, "--"+n)
	}
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "password",
				Source: "--" + n,
			}
		}
		cfg.Password = v
		set("password", configulator.LayerCLI, "--"+n)
	}
	if n := "timeoutSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "timeoutSeconds",
				Source: "--" + n,
			}
		}
		cfg.TimeoutSeconds = v
		set("timeoutSeconds", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Address = &str
			default:
				return configJSONError("address", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError("host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError("port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError("password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  "password",
					Value: "(redacted)",
				}
			}
		case "timeoutSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("timeoutSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("timeoutSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.TimeoutSeconds = &num
			default:
				return configJSONError("timeoutSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "address = %v\n", c.Address)
	fmt.Fprintf(&b, "host = %v\n", c.Host)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	b.WriteString("password = (redacted)\n")
	fmt.Fprintf(&b, "timeoutSeconds = %v\n", c.TimeoutSeconds)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
